test:
  track:
    exp_name: &TEST_NAME "mobilev3_net_19"
    exp_save: &TEST_SAVE "logs"
    model:
      backbone:
        name: "AlexNet"
        AlexNet:
          pretrain_model_path: ""
      losses:
        names: []
      task_head:
        name: "DenseboxHead"
        DenseboxHead:
          total_stride: 8
          score_size: 17
          x_size: 260
          num_conv3x3: 3
          head_conv_bn: [False, False, True]
      task_model:
        name: "SiamTrack"
        SiamTrack:
           pretrain_model_path: "/data/snapshots/mobilev3_net_dist/epoch-19.pkl"
          # pretrain_model_path: "/data/snapshots/nips_ab_backbone_vgg/epoch-19.pkl"
          # pretrain_model_path: "/home/fyk/ijcai2022/siam_fc_transformer3/snap/epoch-19.pkl"
    pipeline:
      name: "SiamFCppTracker"
      SiamFCppTracker:
        test_lr: 0.52
        window_influence: 0.21
        penalty_k: 0.04
        num_conv3x3: 3
    # tester:
    #   names: ["GOT10kTester",]  # (VOTTester|GOT10kTester|LaSOTTester)
    #   GOT10kTester:
    #     exp_name: *TEST_NAME
    #     exp_save: *TEST_SAVE
    #     subsets: ["val"]  # (val|test)
    #     data_root: "/home/fyk/cvprdata"
    #     device_num: 1